# Generated by Django 3.1.2 on 2020-10-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.forumpost')),
            ],
        ),
    ]
