# Generated by Django 3.1.2 on 2020-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_forumreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
