# Generated by Django 3.1.2 on 2020-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_forumpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author_name',
            field=models.TextField(default='no_name', max_length=50),
        ),
    ]
