# Generated by Django 3.1.2 on 2020-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20201013_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='author_name',
            field=models.TextField(default='no_name', max_length=50),
        ),
    ]
