# Generated by Django 3.1.2 on 2020-10-16 06:02

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_forumcomment_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('cover1', models.ImageField(blank=True, null=True, upload_to=general.models.upload_path)),
                ('cover2', models.ImageField(blank=True, null=True, upload_to=general.models.upload_path)),
            ],
        ),
    ]
