# Generated by Django 3.1.2 on 2020-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_userextension_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='bio',
            field=models.CharField(max_length=100),
        ),
    ]
