# Generated by Django 3.1.2 on 2020-10-18 19:11

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20201016_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.upload_profile_photo),
        ),
    ]
