# Generated by Django 3.1.2 on 2020-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_userextension_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
