# Generated by Django 3.1.2 on 2020-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20201107_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='profile_photo',
            field=models.TextField(),
        ),
    ]
