# Generated by Django 3.1.2 on 2020-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20201207_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='bio',
            field=models.CharField(default='No Bio Added', max_length=100),
        ),
    ]
