# Generated by Django 3.1.2 on 2020-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_auto_20201208_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='time',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
