# Generated by Django 3.1.2 on 2021-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20201209_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='file1',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='events',
            name='file2',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
